### ISSUE TITLE
JPEGDEC Error

### ISSUE THREAD

**Issue by psycik** [FirewallDragon/amulet-of-entropy#1]
`no matching function for call to 'JPEGDEC::open(fs::File&, int (*&)(JPEGDRAW*))'" for line: "_jpeg.open(f, jpegDrawCallback);`

Code for open is:
`int open(char *szFilename, JPEG_OPEN_CALLBACK *pfnOpen, JPEG_CLOSE_CALLBACK *pfnClose, JPEG_READ_CALLBACK *pfnRead, JPEG_SEEK_CALLBACK *pfnSeek, JPEG_DRAW_CALLBACK *pfnDraw);`

How did this ever work?

**Comment by FirewallDragon** [comment]
Thanks for reaching out and sorry you hit this issue. Since the code does work for me (and others), the likely culprit an different version of a third party library or some other IDE config/setup parameter.

FWIW, I did have one person reach out to me about this exact issue. He said he fixed it by changing the version of the board package to "Raspberry Pi Pico Version 1.13.3". I can't honestly imagine how this addresses the problem since it has nothing to do with JPEGDEC. And it's an older version of that board package than what I'm using (2.0.3). But maybe he updated other plugins/libraries, as well, which actually fixed the issue for him.

I'm going to go back to the [Setup doc](https://github.com/FirewallDragon/amulet-of-entropy/blob/main/docs/Setup.md) and try to document the versions of each major library I'm using.

**Comment by FirewallDragon** [comment]
I just updated the Setup doc with my local version info and just recompiled the project to verify that it works. You can see the commit delta [here](https://github.com/FirewallDragon/amulet-of-entropy/commit/9632c4042fb9299351d0d0314ec1650c3de80fb8).

**Comment by psycik** [comment]
This is incredibly odd! It now compiles after switching to "2.0.3". Thank you for the quick response.

**Comment by FirewallDragon** [comment]
I just verified this bug when using the latest (v2.3.2) of the Raspberry Pi Pico library. When I reverted to v2.2.2, it compiled. Thanks for bringing this to my attention! I'll document this further in the Setup doc.
